# Generated by Django 2.2 on 2022-12-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0002_auto_20221224_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='palyer_of_match',
            new_name='player_of_match',
        ),
    ]
